name: terraform

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/terraform.yaml
      - '**/*.tf'
      - '**/.terraform.*'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: make
