name: terraform

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/terraform.yaml
      - '**/*.tf'
      - '**/.terraform.*'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
      - run: make

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: terraform-docs/gh-actions@v1
        with:
          git-push: 'true'
