name: terraform

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/terraform.yaml
      - '**/*.tf'
      - '**/.terraform.*'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - run: make
      - uses: int128/update-generated-files-action@v2

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-docs/gh-actions@v1
      - uses: int128/update-generated-files-action@v2
